### PR TITLE
Edit Incident

### PR DESCRIPTION
**Pull request by RandyM1**
Page to edit the title, verticals, type of an Incident.

On hover the fancy border background is shown, to differentiate from clicking on the card to add an update
image

image

### CODE REVIEW

**Comment by Gpx** [comment]
Ohhh a link inside a link, I think Yannick may faint if he saw it.
How about we make the title/date a link for the details and we add a link that says "Edit" or "Update" for the edit page?

**Comment by RandyM1** [comment]
@Gpx I'll remove the link from the Card, add a button to add an Update, and leave the link to update the Incident details.  I think that would be clearer.

**Comment by RandyM1** [comment]
New button.  Card is no longer a link, instead the button links to add an Update.
image

**Comment by RandyM1** [comment]
Also reused the button styling and added a cancel button on the edit Incident page 
image

**Comment by david-piqueres** [comment]
I think it may be better to implement this on the new Incident page instead of on the main page that has all the incidents. That way we can keep the main page how it is at the moment and do the link with the hover in the new Incident page.

What do you think? Sorry for not thinking about it before...

**Comment by RandyM1** [comment]
@david-piqueres The hover is imlemented in home/Incident.tsx.  I guess it should be renamed IncidentCard.tsx.  And we could move the IncidentEdit.* from home to incident.  I'll try the reshuffling.

**Comment by RandyM1** [comment]
@Gpx  New clickable text style, remove the shadow box.
image

**Comment by RandyM1** [comment]
Type is remove from the Incident edit page.  It is only used when creating a new Incident as the type of the first Update when creating the included Update, and any further changes to it will be ignored.

**Comment by RandyM1** [comment]
Final version of the Edit page.  Title changed from Update incident (which is the same when adding an update), this eases the confusion
image

**Pull request merged**
